language: go

go:
  - "1.14.x"
env:
  - GO111MODULE=on

notifications:
  email:
    recipients:
      - kcoewoys@outlook.com

services:
  - docker

before_install:
  - go mod vendor
  - go test -cpu=1,2,4 -v -tags integration ./...
  - go vet $(go list ./... | grep -v /vendor/)
  - make

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - echo "Hello dogo"
  - go test -race  ./... -coverprofile=coverage.txt -covermode=atomic
  - docker build -t kcoewoys/dogo:latest .
  - docker push kcoewoys/dogo:latest


after_success:
   - bash <(curl -s https://codecov.io/bash) -t 9b02bc08-8d9f-41ab-b428-5b173267cf94

